--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.2 (Debian 17.2-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: characters; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.characters (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    born text,
    died text,
    house character varying(255),
    titles text[],
    affiliations text[],
    phrase text,
    description text[],
    profile_image_url text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.characters OWNER TO root;

--
-- Name: characters_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.characters_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.characters_id_seq OWNER TO root;

--
-- Name: characters_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.characters_id_seq OWNED BY public.characters.id;


--
-- Name: houses; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.houses (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    coat_of_arms text,
    words text,
    seat text,
    region text,
    head character varying(255),
    notable_characters text[],
    description text[],
    house_banner_url text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.houses OWNER TO root;

--
-- Name: houses_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.houses_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.houses_id_seq OWNER TO root;

--
-- Name: houses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.houses_id_seq OWNED BY public.houses.id;


--
-- Name: characters id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.characters ALTER COLUMN id SET DEFAULT nextval('public.characters_id_seq'::regclass);


--
-- Name: houses id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.houses ALTER COLUMN id SET DEFAULT nextval('public.houses_id_seq'::regclass);


--
-- Data for Name: characters; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.characters (id, name, born, died, house, titles, affiliations, phrase, description, profile_image_url, created_at, updated_at) FROM stdin;
1	Jon Snow	As Aegon Targaryen, 281 AC, Tower Of Joy, Dorne	302 AC, Castle Black, later resurrected	Targaryen	{"Lord Commander of the Night's Watch","King in the North","Warden Of The North"}	{"Night's Watch","House Stark"}	My Watch Has Ended	{"Jon Snow, born Aegon Targaryen, is the son of Lyanna Stark and Rhaegar Targaryen, the late Prince of Dragonstone. To protect him from those seeking to destroy House Targaryen, Jon is presented as the illegitimate son of Lord Eddard Stark, Lyanna's brother, and raised at Winterfell alongside Eddard's legitimate children. His true parentage remains a closely guarded secret, even from Jon himself.","As a young man, Jon joins the Night's Watch and eventually becomes Lord Commander. However, his leadership sparks controversy, particularly his decision to allow the wildlings to settle south of the Wall. These decisions lead to his murder in a mutiny, but he is brought back to life by the red priestess Melisandre.","Freed from his vows to the Night's Watch after his resurrection, Jon teams up with his half-sister Sansa Stark to reclaim Winterfell from House Bolton, restoring House Stark's rule in the North. He is then proclaimed King in the North.","When the threat of the White Walkers looms, Jon negotiates an alliance with Daenerys Targaryen. He pledges himself and his forces to her cause, falling in love with her in the process. Jon abdicates his title as King in the North and becomes Warden of the North under Daenerys.","Later, Jon learns from Samwell Tarly that he is actually Aegon Targaryen, making Daenerys his aunt. As a dragonrider bonded with Rhaegal, Jon fights in the Battle of Winterfell, where the Night King is defeated and the Long Night is averted. Following the victory, Jon supports Daenerys in her campaign for the Iron Throne and takes part in the Battle of King's Landing.","However, when Daenerys destroys a surrendered King's Landing, Jon realizes he cannot dissuade her from further devastation. To prevent more bloodshed, he reluctantly kills her.","After Daenerys' death, a Great Council convenes and decides Jon's fate. He is exiled back to the Night's Watch. There, Jon leads the Free Folk to settle in the thawing lands beyond the Wall, embracing a life of freedom."}	/images/jon-snow.webp	2025-01-23 14:10:24.331866+00	2025-01-23 14:10:24.331866+00
2	Daenerys Targaryen	At the end of Robert's Rebellion, 284 AC, Dragonstone	305 AC, Red Keep, King's Landing	Targaryen	{"Queen of Meereen","Queen of the Andals, the Rhoynar, and the First Men","Khaleesi of the Great Grass Sea","Protector of the Realm","Lady Regent of the Seven Kingdoms","Lady of Dragonstone"}	{"House Targaryen","House Stark","House Greyjoy"}	Dracarys	{"Daenerys Targaryen, known as Daenerys Stormborn, is the daughter of King Aerys II Targaryen and Queen Rhaella Targaryen, and the younger sister of Rhaegar and Viserys Targaryen. She was born at the end of Robert's Rebellion on Dragonstone, after her family was deposed from the Iron Throne and her mother died giving birth to her.","Raised in exile in Essos, Daenerys grows up under the care of her abusive brother Viserys. She is eventually married off to Khal Drogo, the leader of a Dothraki khalasar, in exchange for an army that Viserys hopes to use to reclaim the Iron Throne.","After Drogo's death, Daenerys assumes leadership of the khalasar and begins to build her own following. She hatches three dragon eggs gifted to her at her wedding, birthing Drogon, Rhaegal, and Viserion, becoming the first person in over a century to own dragons.","Daenerys embarks on a campaign to free the oppressed people of Slaver's Bay. She conquers several cities, including Astapor, Yunkai, and Meereen, where she establishes herself as the ruler and attempts to abolish slavery.","Eventually, Daenerys sets her sights on reclaiming the Iron Throne. She sails to Westeros with her army, dragons, and newfound allies, including Tyrion Lannister, whom she appoints as Hand of the Queen.","She forms an alliance with Jon Snow, whom she later falls in love with, to fight the Night King and his army of the dead. After the Battle of Winterfell, where the Night King is defeated, Daenerys resumes her campaign for the Iron Throne.","In the Battle of King's Landing, Daenerys uses her dragon, Drogon, to destroy the city, even after its surrender. Her actions lead to widespread devastation and loss of life.","In the aftermath, Jon Snow, realizing Daenerys' unyielding determination to \\"liberate\\" the world, reluctantly kills her to prevent further bloodshed. Her body is carried away by Drogon, disappearing into the unknown."}	/images/daenerys-targaryen.webp	2025-01-23 14:12:06.032185+00	2025-01-23 14:12:06.032185+00
3	Tyrion Lannister	273 AC, Casterly Rock	\N	Lannister	{"Hand of the King","Hand of the Queen","Master of Coin"}	{"House Lannister","House Targaryen"}	I drink and I know things	{"Tyrion Lannister is the youngest son of Lord Tywin Lannister and younger brother of Jaime and Cersei Lannister. He is a dwarf, and his stature has earned him the nickname \\"The Imp\\" and \\"The Halfman\\".","Tyrion is intelligent and witty, and he uses his sharp mind and quick tongue to navigate the dangerous political landscape of Westeros. Despite being a Lannister, he is often looked down upon by his father and sister due to his physical appearance and the belief that he caused their mother's death during childbirth.","He initially serves as Hand of the King to his nephew, King Joffrey Baratheon, where he plays a crucial role in defending King's Landing during the Battle of the Blackwater. However, after being accused of Joffrey's murder, he escapes execution with the help of his brother Jaime and flees to Essos.","In Essos, Tyrion meets Daenerys Targaryen and becomes one of her trusted advisors, eventually serving as her Hand of the Queen. He helps her strategize and form alliances, using his political acumen to aid her quest to reclaim the Iron Throne.","Despite his loyalty to Daenerys, he grows increasingly troubled by her methods and the destruction she causes. After the devastation of King's Landing, he ultimately betrays her by conspiring to have Jon Snow kill her to prevent further bloodshed.","Following Daenerys' death, Tyrion is imprisoned but later released by the newly formed Great Council. He becomes Hand of the King once more, this time serving Bran Stark, and helps to establish a more stable and just rule in Westeros."}	/images/tyrion-lannister.webp	2025-01-23 14:28:07.154172+00	2025-01-23 14:28:07.154172+00
5	Cersei Lannister	266 AC, Casterly Rock	305 AC, Red Keep, King's Landing	Lannister	{"Queen of the Seven Kingdoms","Lady of Casterly Rock"}	{"House Lannister"}	When you play the game of thrones, you win or you die	{"Cersei Lannister is the eldest daughter of Lord Tywin Lannister and twin sister of Jaime Lannister. As a member of House Lannister, one of the wealthiest and most powerful families in Westeros, Cersei is fiercely ambitious and determined to maintain her family's dominance.","She is initially married to King Robert Baratheon, becoming the Queen of the Seven Kingdoms. Her marriage to Robert is loveless and tumultuous, leading Cersei to seek comfort in her incestuous relationship with her brother Jaime. The three children she bears—Joffrey, Myrcella, and Tommen—are all fathered by Jaime, though they are publicly presented as Robert's legitimate heirs.","Cersei's ambition and ruthlessness drive many of her actions as she manipulates and schemes to secure power for herself and her children. Her intelligence and cunning make her a formidable political player, often outmaneuvering her rivals and enemies.","After the deaths of her children and the capture of King's Landing by the Faith Militant, Cersei seizes power by orchestrating a devastating explosion that destroys the Great Sept of Baelor, eliminating her enemies in one stroke. She then crowns herself Queen of the Seven Kingdoms.","As Queen, Cersei faces numerous challenges, including the threat of Daenerys Targaryen and her dragons, and the advancing army of the dead from the North. Despite her efforts to maintain control, she ultimately loses the support of key allies and is left increasingly isolated.","In the final stages of her reign, Cersei's attempts to hold onto power become increasingly desperate. She reunites with Jaime, who returns to King's Landing to be with her in her final moments. Both siblings perish together in the Red Keep as it collapses during the Battle of King's Landing, buried under the rubble of their ruined dynasty."}	/images/cersei-lannister.webp	2025-01-23 14:30:19.474889+00	2025-01-23 14:30:19.474889+00
4	Jaime Lannister	266 AC, Casterly Rock	305 AC, Red Keep, King's Landing	Lannister	{"Lord Commander of the Kingsguard","Warden of the West",Kingslayer}	{"House Lannister",Kingsguard}	The things I do for love	{"Jaime Lannister is the eldest son of Lord Tywin Lannister and the twin brother of Queen Cersei Lannister. Known as the \\"Kingslayer\\" for killing King Aerys II Targaryen during Robert's Rebellion, Jaime is initially depicted as an arrogant and skilled knight.","He serves as a member of the Kingsguard and later becomes the Lord Commander. Despite his reputation as a dishonorable man for breaking his vow to protect the king, Jaime's actions are revealed to be motivated by his desire to protect the innocent from Aerys' madness.","Jaime's relationship with his sister Cersei is a defining aspect of his character. The two have a secret incestuous relationship, which results in the birth of their three children, whom they publicly claim are the children of King Robert Baratheon.","Captured by Robb Stark's forces during the War of the Five Kings, Jaime is eventually freed by Catelyn Stark in exchange for promising to return her daughters. During his journey back to King's Landing, Jaime forms a bond with Brienne of Tarth, which leads to his transformation into a more honorable person.","He loses his right hand, which profoundly affects his identity and fighting skills, but also leads to personal growth and reflection. Jaime eventually returns to King's Landing, where he helps Cersei seize power.","Despite his loyalty to Cersei, Jaime becomes increasingly disillusioned with her actions. He leaves her to fight in the North against the White Walkers, and later returns to King's Landing in an attempt to save her. However, both Jaime and Cersei die together in the Red Keep during the Battle of King's Landing, buried beneath the rubble as the city falls."}	/images/jaime-lannister.webp	2025-01-23 14:29:38.467111+00	2025-01-23 14:29:38.467111+00
8	Eddard Stark	263 AC, Winterfell	299 AC, King's Landing	Stark	{"Lord of Winterfell","Warden of the North","Hand of the King"}	{"House Stark","House Baratheon"}	Winter is Coming	{"Eddard Stark, often called Ned, is the head of House Stark and Lord of Winterfell. He is known for his honor, integrity, and sense of duty. Eddard is a close friend of King Robert Baratheon, having fought alongside him during Robert's Rebellion.","Ned is married to Catelyn Stark, with whom he has five children: Robb, Sansa, Arya, Bran, and Rickon. He also raises Jon Snow, his illegitimate son, as his own at Winterfell.","Despite his reluctance, Ned becomes Hand of the King at Robert's request and moves to King's Landing with his daughters Sansa and Arya. There, he discovers the truth about the parentage of Robert's supposed children, which leads to his conflict with Queen Cersei Lannister.","Ned's unwavering commitment to the truth and his sense of honor ultimately lead to his downfall. He is betrayed by Petyr Baelish and imprisoned by the Lannisters. Despite confessing to treason in a bid to save his family, Ned is executed on the orders of King Joffrey Baratheon.","Ned's death sets off a series of events that plunge the Seven Kingdoms into chaos and war. His legacy lives on through his children, who each carry a part of his honor and sense of duty as they navigate their own paths."}	/images/ned-stark.webp	2025-01-23 14:32:39.374517+00	2025-01-23 14:32:39.374517+00
6	Tywin Lannister	242 AC, Casterly Rock	300 AC, King's Landing	Lannister	{"Hand of the King","Lord of Casterly Rock","Warden of the West"}	{"House Lannister"}	A lion does not concern himself with the opinion of sheep	{"Tywin Lannister is the head of House Lannister, one of the wealthiest and most powerful families in Westeros. He is the father of Jaime, Cersei, and Tyrion Lannister, and is known for his formidable political acumen, ruthless nature, and dedication to his family's legacy.","Tywin serves as Hand of the King to King Aerys II Targaryen, earning a reputation as an effective and efficient ruler. After Robert's Rebellion, he supports Robert Baratheon's claim to the throne and becomes one of his key advisors.","Tywin is deeply pragmatic and values loyalty, honor, and family above all else. He is particularly harsh and unforgiving towards his youngest son, Tyrion, whom he blames for the death of his wife, Joanna, during childbirth.","Despite his disdain for Tyrion, Tywin ultimately appoints him as Acting Hand of the King in his absence, recognizing his intelligence and political skill. Tywin himself remains a central figure in the power struggles of Westeros, orchestrating several key alliances and military victories.","His relentless pursuit of power and control, however, ultimately leads to his downfall. After discovering Tywin's plan to have him executed, Tyrion escapes his imprisonment and confronts his father. In a moment of defiance, Tyrion kills Tywin, bringing an end to his ruthless rule and leaving a significant power vacuum in King's Landing."}	/images/tywin-lannister.webp	2025-01-23 14:31:19.630034+00	2025-01-23 14:31:19.630034+00
7	Sansa Stark	286 AC, Winterfell	\N	Stark	{"Lady of Winterfell","Queen in the North"}	{"House Stark","House Lannister (formerly)","House Bolton (formerly)","Knights of the Vale"}	The North remembers	{"Sansa Stark is the eldest daughter of Lord Eddard Stark and Lady Catelyn Stark of Winterfell. She is known for her beauty, her grace, and her adherence to the traditional feminine virtues of her upbringing. Throughout her journey, Sansa evolves from a naive girl dreaming of courtly romance to a wise and resilient leader.","Sansa's life changes dramatically when she is betrothed to Prince Joffrey Baratheon and moves to King's Landing. Her experiences there are harsh and traumatic, including witnessing her father's execution and suffering abuse at Joffrey's hands. Her time in the capital teaches her the dangers and intrigues of political life.","After Joffrey's death, Sansa is forced to marry Tyrion Lannister, though their marriage is never consummated. She later escapes King's Landing with the help of Petyr Baelish (Littlefinger), who becomes her mentor and protector. He takes her to the Vale, where she learns to navigate the complexities of power.","Sansa's trials continue when she is married to Ramsay Bolton, a sadistic and cruel man. Her marriage to Ramsay is a period of immense suffering, but she ultimately escapes with the help of Theon Greyjoy.","Reuniting with her half-brother Jon Snow, Sansa plays a crucial role in retaking Winterfell from the Boltons and restoring House Stark's rule in the North. Her leadership, resilience, and strategic thinking earn her the respect and loyalty of the Northern lords.","As the threat of the White Walkers looms, Sansa supports Jon's efforts to forge alliances and prepare for the battle against the undead. Following the defeat of the Night King, Sansa focuses on securing the North's independence from the Iron Throne.","In the aftermath of the war, Sansa is declared the Queen in the North, leading the North as an independent kingdom. Her journey from a sheltered girl to a powerful and wise ruler is one of growth, strength, and resilience."}	/images/sansa-stark.webp	2025-01-23 14:32:00.668572+00	2025-01-23 14:32:00.668572+00
\.


--
-- Data for Name: houses; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.houses (id, name, coat_of_arms, words, seat, region, head, notable_characters, description, house_banner_url, created_at, updated_at) FROM stdin;
3	House Lannister	A golden lion rampant on a crimson field	Hear Me Roar!	Casterly Rock	The Westerlands	Tywin Lannister	{"Tywin Lannister","Jaime Lannister","Cersei Lannister","Tyrion Lannister"}	{"House Lannister of Casterly Rock is one of the Great Houses of Westeros and the principal noble house in the Westerlands. Their seat is Casterly Rock, a massive rock beside the Sunset Sea. The Lannisters are one of the richest and most powerful families in the Seven Kingdoms, largely due to their extensive gold mines. Their words are 'Hear Me Roar!' but their unofficial motto, 'A Lannister Always Pays His Debts,' is more widely known.","Tywin Lannister, known for his ruthlessness and political acumen, served as Hand of the King to several kings. He orchestrated key alliances and victories, solidifying the Lannisters' power. Tywin is a formidable leader, and his death leaves a significant power vacuum in the realm.","Jaime Lannister, Tywin's eldest son, is known as the Kingslayer for killing King Aerys II Targaryen during Robert's Rebellion. Despite his reputation, Jaime's complex character and journey reveal his struggles with honor and loyalty.","Cersei Lannister, Tywin's only daughter, is fiercely ambitious and determined to maintain her family's dominance. She becomes Queen of the Seven Kingdoms and is known for her cunning and ruthless tactics to achieve her goals. Her love for her children drives many of her actions, and her downfall is marked by the loss of her children and the eventual destruction of King's Landing.","Tyrion Lannister, the youngest son, is intelligent and witty. Despite being despised by his father and sister for his stature and birth, Tyrion proves to be a shrewd political player. He serves as Hand of the Queen to Daenerys Targaryen and later becomes Hand of the King to Bran Stark."}	/images/house-lannister.webp	2025-01-23 14:47:21.06741+00	2025-01-23 14:47:21.06741+00
1	House Stark	A grey direwolf on a white field	Winter is Coming	Winterfell	The North	Eddard Stark	{"Eddard Stark","Robb Stark","Sansa Stark","Arya Stark","Bran Stark","Rickon Stark","Jon Snow"}	{"House Stark of Winterfell is one of the Great Houses of Westeros and the principal noble house in the North. Their ancestral seat is Winterfell, one of the oldest and most storied castles in the Seven Kingdoms. The Starks have ruled the North for thousands of years, tracing their lineage back to the Age of Heroes and the legendary Bran the Builder, who is said to have constructed both Winterfell and the Wall. Their motto, 'Winter is Coming,' serves as a reminder of the harsh realities they face and their duty to protect the realm.","Eddard Stark, commonly known as Ned, was the head of House Stark at the beginning of the series. Known for his unwavering sense of honor and duty, Ned played a key role in Robert's Rebellion, which led to the overthrow of the Targaryen dynasty. He was later appointed Hand of the King to his old friend, Robert Baratheon. However, his pursuit of justice and truth ultimately led to his downfall and execution, sparking the War of the Five Kings.","The Stark family is known for their strong sense of loyalty, honor, and duty. Each member of the family embodies different aspects of these traits. Robb Stark, Ned's eldest son, took up the mantle of King in the North and fought valiantly to avenge his father and reclaim the North. Sansa Stark, initially a naive girl, grows into a wise and resilient leader who plays a crucial role in reclaiming Winterfell and securing the North's independence. Arya Stark, fierce and determined, trains as an assassin and avenges her family's wrongs. Bran Stark, after a harrowing journey beyond the Wall, becomes the enigmatic Three-Eyed Raven. Jon Snow, raised as Ned's illegitimate son, proves to be a natural leader and ultimately learns of his true heritage as Aegon Targaryen.","House Stark's history is marked by their steadfastness, their resilience in the face of adversity, and their commitment to protecting the realm. The words 'Winter is Coming' reflect their understanding of the transient nature of power and the ever-present threat of the unknown. Despite the many trials and tribulations they face, the Stark family remains a symbol of enduring honor and integrity in Westeros."}	/images/house-stark.webp	2025-01-23 14:45:12.646792+00	2025-01-23 14:45:12.646792+00
5	House Tyrell	A golden rose on a green field	Growing Strong	Highgarden	The Reach	Mace Tyrell	{"Mace Tyrell","Olenna Tyrell","Loras Tyrell","Margaery Tyrell"}	{"House Tyrell of Highgarden is one of the Great Houses of Westeros and the principal noble house in the Reach. Their seat is Highgarden, a magnificent castle and a center of chivalry and courtly love. The Tyrells are known for their wealth, vast armies, and fertile lands. Their sigil is a golden rose on a green field, and their words are 'Growing Strong,', reflecting their prosperous and resilient nature.","Mace Tyrell, the head of the house, is an ambitious yet often underappreciated leader. He holds several key positions, including Lord of Highgarden and Warden of the South. Despite his occasional bumbling demeanor, he is a capable commander and a loyal supporter of the ruling powers.","Olenna Tyrell, also known as the Queen of Thorns, is the matriarch of the family and a formidable political player. Sharp-witted and cunning, Olenna is a master strategist who orchestrates several key alliances and maneuvers to elevate House Tyrell's standing in the realm.","Loras Tyrell, known as the Knight of Flowers, is celebrated for his martial prowess and chivalry. He is a skilled and courageous knight who earns the admiration of many, both on and off the battlefield.","Margaery Tyrell, the daughter of Mace Tyrell, is known for her beauty, charm, and intelligence. She skillfully navigates the complex politics of King's Landing, marrying three kings (Renly Baratheon, Joffrey Baratheon, and Tommen Baratheon) in her quest for power. Margaery's ability to win the hearts of the people and her philanthropic efforts make her a beloved figure in the capital.","House Tyrell's influence and power grow significantly during the War of the Five Kings, as they ally with House Lannister to defeat Stannis Baratheon at the Battle of Blackwater. Despite their growing influence, the Tyrells face numerous challenges and betrayals, leading to their tragic downfall in the events that follow."}	/images/house-tyrell.webp	2025-01-23 14:49:44.213927+00	2025-01-23 14:49:44.213927+00
7	House Martell	A red sun pierced by a gold spear, on an orange field	Unbowed, Unbent, Unbroken	Sunspear	Dorne	Doran Martell	{"Doran Martell","Elia Martell","Oberyn Martell","Arianne Martell","Trystane Martell"}	{"House Martell of Sunspear is one of the Great Houses of Westeros and the principal noble house in Dorne. Their seat is Sunspear, a castle located in the southernmost region of Westeros. House Martell is known for its fierce independence, resistance to conquest, and its unique customs and culture, which set it apart from the rest of the Seven Kingdoms. Their sigil is a red sun pierced by a gold spear on an orange field, and their words are 'Unbowed, Unbent, Unbroken,' reflecting their resilience and determination.","Doran Martell, the head of the house, is a wise and patient ruler. Though he suffers from gout and is physically weakened, his mind remains sharp, and he navigates the political landscape with caution and foresight. He values the safety and prosperity of Dorne and is deeply affected by the loss of his sister, Elia Martell.","Elia Martell, the younger sister of Doran, was married to Prince Rhaegar Targaryen and had two children with him. During Robert's Rebellion, she and her children were brutally murdered by Ser Gregor Clegane on the orders of Tywin Lannister, an event that left a lasting impact on the Martell family.","Oberyn Martell, known as the Red Viper, is the younger brother of Doran and a formidable warrior. He is known for his deadly combat skills, sharp wit, and passionate nature. Oberyn seeks justice for the murder of his sister Elia and ultimately meets his end in a trial by combat against Ser Gregor Clegane.","Arianne Martell, the eldest daughter of Doran and heir to Sunspear, is intelligent, ambitious, and fiercely loyal to her family. She plays a key role in Dorne's political intrigues and has her own aspirations for the future of her house.","Trystane Martell, the youngest son of Doran, is betrothed to Myrcella Baratheon as part of a political alliance with the Lannisters. He is kind-hearted and honorable, embodying the values of his house.","House Martell is known for its distinct culture and customs, including the equal status of men and women in inheritance and leadership. The Martells have long resisted the rule of the Iron Throne, maintaining their independence through both diplomacy and warfare. Their history is marked by their fierce defense of their homeland, their unique traditions, and their enduring spirit."}	/images/house-martell.webp	2025-01-23 14:51:42.321709+00	2025-01-23 14:51:42.321709+00
9	House Targaryen	A red three-headed dragon on a black field	Fire and Blood	Dragonstone	Crownlands	Daenerys Targaryen	{"Aegon I Targaryen","Aerys II Targaryen","Rhaegar Targaryen","Viserys Targaryen","Daenerys Targaryen"}	{"House Targaryen of Dragonstone is one of the Great Houses of Westeros and the former royal house of the Seven Kingdoms. The Targaryens originally came from the ancient civilization of Valyria and were one of the few families of dragonlords to survive the Doom of Valyria. They established their seat on the island of Dragonstone before Aegon the Conqueror launched his campaign to conquer the Seven Kingdoms, which became known as Aegon's Conquest. Their sigil is a red three-headed dragon on a black field, and their words are 'Fire and Blood,' reflecting their fiery nature and their connection to dragons.","Aegon I Targaryen, known as Aegon the Conqueror, was the first Targaryen king to sit on the Iron Throne. He, along with his sister-wives Visenya and Rhaenys, united the Seven Kingdoms under Targaryen rule through conquest and the might of their dragons. Aegon's establishment of the Iron Throne marked the beginning of the Targaryen dynasty in Westeros.","Aerys II Targaryen, also known as the Mad King, was the last Targaryen to rule the Seven Kingdoms. His descent into madness and tyranny led to widespread unrest and ultimately sparked Robert's Rebellion. Aerys was overthrown and killed during the rebellion, bringing an end to nearly three centuries of Targaryen rule.","Rhaegar Targaryen, the eldest son of Aerys II, was a noble and charismatic prince who met a tragic end at the Battle of the Trident during Robert's Rebellion. His actions and relationships played a significant role in the events leading up to the rebellion.","Viserys Targaryen, the younger brother of Rhaegar, lived in exile after the fall of the Targaryen dynasty. His ambition to reclaim the Iron Throne drove him to seek alliances and support, but his arrogance and cruelty ultimately led to his downfall.","Daenerys Targaryen, the last surviving member of the Targaryen family, emerges as a powerful and determined leader. Born during the tumultuous final days of Robert's Rebellion, Daenerys grows up in exile in Essos. She rises to power by liberating slaves, commanding armies, and hatching three dragons. Her quest to reclaim the Iron Throne leads her to Westeros, where she forms alliances and confronts formidable enemies. Despite her initial successes, her ambition and the destructive power of her dragons result in her tragic end."}	/images/house-targaryen.webp	2025-01-23 14:54:22.015325+00	2025-01-23 14:54:22.015325+00
8	House Greyjoy	A golden kraken on a black field	We Do Not Sow	Pyke	The Iron Islands	Balon Greyjoy	{"Balon Greyjoy","Euron Greyjoy","Asha Greyjoy","Theon Greyjoy"}	{"House Greyjoy of Pyke is one of the Great Houses of Westeros and the principal noble house in the Iron Islands. Their seat is Pyke, a castle located on the island of the same name. The Greyjoys are known for their seafaring prowess, their fierce independence, and their adherence to the Old Way of reaving and raiding. Their sigil is a golden kraken on a black field, and their words are 'We Do Not Sow,' reflecting their reliance on taking what they need rather than producing it themselves.","Balon Greyjoy, the head of the house at the beginning of the series, leads a failed rebellion against the Iron Throne known as the Greyjoy Rebellion. Following his defeat, Balon submits to the rule of the Iron Throne, but his desire for independence and sovereignty over the Iron Islands never wanes. He later declares himself King of the Iron Islands once more and seeks to reclaim his ancestral rights.","Euron Greyjoy, Balon's younger brother, is a ruthless and ambitious pirate who returns to the Iron Islands after years of exile. Known for his cunning and brutality, Euron seizes control of the Iron Islands after Balon's death and sets his sights on conquering the Seven Kingdoms.","Asha Greyjoy, Balon's daughter, is a fierce and capable leader who commands her own ship and crew. She challenges the traditional male-dominated leadership of the Ironborn and seeks to become the ruler of the Iron Islands. Asha is known for her intelligence, bravery, and determination.","Theon Greyjoy, Balon's youngest son, is taken as a ward by Eddard Stark following the Greyjoy Rebellion. Raised at Winterfell alongside the Stark children, Theon struggles with his divided loyalties between his birth family and the Starks. His quest for identity and redemption is a central theme in his character arc.","House Greyjoy is defined by their maritime culture and their desire for autonomy from the mainland. Their history is marked by their efforts to assert their independence, their participation in raiding and piracy, and their complex relationships with other noble houses. Despite their tumultuous history, the Greyjoys remain a powerful and influential force in the Iron Islands and beyond."}	/images/house-greyjoy.webp	2025-01-23 14:53:23.625593+00	2025-01-23 14:53:23.625593+00
6	House Arryn	A sky-blue falcon soaring against a white moon, on a sky-blue field	As High as Honor	The Eyrie	The Vale of Arryn	Robin Arryn	{"Jon Arryn","Lysa Arryn","Robin Arryn","Harrold Hardyng"}	{"House Arryn of the Eyrie is one of the oldest and most noble houses of Westeros, and the principal noble house in the Vale of Arryn. Their seat is the Eyrie, a castle high in the mountains that is considered impregnable. The Arryns are descendants of the Kings of Mountain and Vale, and their sigil is a sky-blue falcon soaring against a white moon on a sky-blue field. Their words are 'As High as Honor,' reflecting their lofty ideals and elevated position.","Jon Arryn, the head of the house at the beginning of the series, served as Hand of the King to Robert Baratheon and was a father figure to both Eddard Stark and Robert. His mysterious death sets off the events of the series, as his investigation into the legitimacy of Robert's children leads to his murder.","Lysa Arryn, Jon's widow and the younger sister of Catelyn Stark, is fiercely protective of her son, Robin Arryn. She rules the Vale in her son's name and becomes increasingly unstable and paranoid after her husband's death. Lysa is eventually killed by Petyr Baelish, who manipulates her and seizes control of the Vale.","Robin Arryn, the young and sickly son of Jon and Lysa, becomes the Lord of the Eyrie after his father's death. Under the guardianship of Petyr Baelish, Robin's rule is characterized by his inexperience and naivety. He is eventually poised to be replaced by Harrold Hardyng, a distant cousin, as heir to the Vale.","House Arryn is known for its strong martial traditions and its long-standing loyalty to the Targaryens during their rule. Their strategic position in the Vale and their impregnable seat at the Eyrie make them a formidable power in the region. Despite the internal strife and external pressures, House Arryn remains a symbol of honor and strength in the Vale."}	/images/house-arryn.webp	2025-01-23 14:50:30.702838+00	2025-01-23 14:50:30.702838+00
4	House Baratheon	A black stag on a gold field	Ours is the Fury	Storm's End	The Stormlands	Robert Baratheon	{"Robert Baratheon","Stannis Baratheon","Renly Baratheon"}	{"House Baratheon of Storm's End is one of the Great Houses of Westeros and the principal noble house in the Stormlands. Their seat is Storm's End, a massive fortress located on the southeastern coast of Westeros. House Baratheon was founded by Orys Baratheon, a legendary figure who served as a general in Aegon the Conqueror's army and was said to be his bastard brother. The house's sigil is a black stag on a gold field, and their words are 'Ours is the Fury,' reflecting their fierce and tempestuous nature.","Robert Baratheon, the eldest of three brothers, led the rebellion against the Mad King Aerys II Targaryen, which became known as Robert's Rebellion. With the support of House Stark, House Arryn, and House Tully, Robert successfully overthrew the Targaryen dynasty and ascended to the Iron Throne, becoming the King of the Seven Kingdoms.","Stannis Baratheon, the middle brother, is known for his stern and rigid sense of duty. He served as Master of Ships on Robert's Small Council and later declared himself King of the Seven Kingdoms after Robert's death, challenging the legitimacy of his nephew Joffrey Baratheon. Stannis is a skilled military commander and a determined leader, but his rigid adherence to duty and his alliance with the red priestess Melisandre ultimately lead to his downfall.","Renly Baratheon, the youngest brother, is charismatic and charming. He also declares himself King of the Seven Kingdoms after Robert's death, with the support of the powerful House Tyrell. However, his ambitions are cut short when he is assassinated under mysterious circumstances, suspected to be the work of Stannis' sorcery.","House Baratheon's history is marked by their boldness and ambition. Robert's reign as king is characterized by his larger-than-life personality and his attempts to maintain peace and stability in the realm. The internal conflicts among the Baratheon brothers after Robert's death further exemplify their fierce and tumultuous nature. Despite their individual differences, the Baratheon brothers each leave a significant impact on the political landscape of Westeros."}	/images/house-baratheon.webp	2025-01-23 14:48:07.39784+00	2025-01-23 14:48:07.39784+00
10	House Tully	A silver trout leaping on a blue and red striped field	Family, Duty, Honor	Riverrun	The Riverlands	Edmure Tully	{"Hoster Tully","Catelyn Stark","Lysa Arryn","Edmure Tully","Brynden Tully"}	{"House Tully of Riverrun is one of the Great Houses of Westeros and the principal noble house in the Riverlands. Their seat is Riverrun, a large castle situated at the confluence of the Red Fork of the Trident. The Tullys are known for their strong sense of duty, loyalty, and family values. Their sigil is a silver trout leaping on a blue and red striped field, and their words are 'Family, Duty, Honor,' reflecting their commitment to these core principles.","Hoster Tully, the head of the house at the beginning of the series, is a seasoned and respected lord who plays a significant role in Robert's Rebellion. He forges important alliances through the marriages of his daughters, Catelyn and Lysa, to key figures in the rebellion.","Catelyn Stark, the eldest daughter of Hoster, becomes Lady of Winterfell through her marriage to Eddard Stark. She is a devoted wife and mother who takes an active role in the political and military struggles of her family, seeking justice for the wrongs committed against them.","Lysa Arryn, the younger daughter of Hoster, marries Jon Arryn and becomes Lady of the Eyrie. Her life is marked by tragedy and instability, and her actions significantly impact the political landscape of the Seven Kingdoms.","Edmure Tully, the heir to Riverrun, is a well-meaning but often inept leader. Despite his shortcomings, he remains loyal to his family and their cause, participating in the War of the Five Kings and enduring imprisonment during the conflict.","Brynden Tully, known as the Blackfish, is Hoster's younger brother and a formidable warrior. He is a staunch defender of his family and their lands, playing a key role in several battles and sieges throughout the series.","House Tully's history is marked by their dedication to family and their sense of duty. Their strategic location in the Riverlands makes them influential in the politics and conflicts of Westeros. Despite the challenges they face, the Tullys remain committed to their values and continue to play a significant role in the realm."}	/images/house-tully.webp	2025-01-23 14:54:58.896221+00	2025-01-23 14:54:58.896221+00
\.


--
-- Name: characters_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.characters_id_seq', 8, true);


--
-- Name: houses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: root
--

SELECT pg_catalog.setval('public.houses_id_seq', 10, true);


--
-- Name: characters characters_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_pkey PRIMARY KEY (id);


--
-- Name: houses houses_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.houses
    ADD CONSTRAINT houses_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

